### ISSUE TITLE
Unintuitive search results

### ISSUE THREAD

**Issue by ZibingZhang** [sandboxnu/searchneu-v1#152]
## Issue

I'm getting back vastly different and unexpected results when my query differs by a single space.

## Replicate 

For the spring 2022 semester...

If we search `eece2322`, the first result is `EECE 2322: Fundamentals of Digital Design and Computer Organization`, which is what I would expect.

However, if we search `eece 2322`, the aforementioned class is the fifth result.

I think that this behavior isn't very intuitive. Since the course code contains a space in it, I would imagine most people would tend to search for their class with the space. It was only after a bit of tinkering around that I realized that omitting the space fixed the issue.

**Comment by hankewyczz** [comment]
Thanks - this is unintentional behavior caused by a bug in the backend. I'm actually working on a PR for this issue right now - should be back to normal soon.

If you're curious, any query matching the regex `/^\s*([a-zA-Z]{2,4})\s*(\d{4})?\s*$/i` should have the same behavior (so both the ones you listed should act the same)
