### ISSUE TITLE
Next.js

### ISSUE THREAD

**Issue by gamburgm** [sandboxnu/searchneu-v1#49]
# Goal
Next.js means a few things:
1. We can make SearchNEU serverless
2. Code organization is much cleaner, and we can delete a bunch of crap (e.g. React Router)
3. We can speed up load times with server rendering and code splitting

# Design
1. Re-structure the frontend to use Next.js, but leave current backend alone
2. Add Vercel integration
3. post-split, add a route for the notification workflow code

Once the above is finished, we can toss the backend code (in theory).

**Comment by dajinchu** [comment]
TODOS:


- [x] SVG support. One of these methods: https://stackoverflow.com/questions/55175445/cant-import-svg-into-next-js
- [x] Amplitude/GA/Rollbar/Fullstory imports
- [x] usequeryparms
- [x] check index.html stuff
- [x] google font
- [x] get jest running again
- [x] boston skyline not full width at wide layouts for some reason
- [x] searchneu logo sometimes flashes weirdly on first load
- [x] Various window not defined errors

**Comment by NEUDitao** [comment]
Did some fun debugging in the meantime:


**Operation No Husky**
for some reason, the Husky appears only if the sandbox logo is deleted? getting rid of the classes on the new SVG components didn't help.

This is with `SandboxLogo` still there
![image](https://user-images.githubusercontent.com/33675688/103166164-614a1b80-47ed-11eb-8367-d439a7f1a829.png)

When you delete `SandboxLogo` 🤔 
![image](https://user-images.githubusercontent.com/33675688/103166169-6a3aed00-47ed-11eb-9f44-97fdad99b235.png)


**Images not Stacking**

Since Next.js `<Image>`s are imgs wrapped in a div, the images actually appear not stacked any more. Think this might be a css thing now -- we might have to do the whole "bottom element is `relative`, top element is `absolute` thing.

Locally:
![image](https://user-images.githubusercontent.com/33675688/103166176-7de65380-47ed-11eb-8605-2dbb05966066.png)

Production:
![image](https://user-images.githubusercontent.com/33675688/103166197-b0904c00-47ed-11eb-8e71-af06f05d07f8.png)

**Comment by NEUDitao** [comment]
There is a simulacrum of the results page working

![image](https://user-images.githubusercontent.com/33675688/103167377-aaec3380-47f8-11eb-8938-9a79614c4974.png)

## Things that require TLC

things you'll wanna look at really heavily for some TENDER LOVE and CARE is /pages/[termId]/[query].tsx
12:57
funnily enough, searching using the search bar both updates the query and returns the correct query correctly
12:58
https://github.com/sandboxnu/searchneu/blob/57c530b114eba9484e80c5bdf9437da78a1c9c4f/pages/%5BtermId%5D/%5Bquery%5D.tsx#L122 i'm pretty sure it's because I got rid of this line -- so we have no way of dispatching the correct campus or term currently -- oopsies. probably just want to move termId and campus into some useStates and then update the router appropriately -- not too hard to do


https://github.com/sandboxnu/searchneu/blob/57c530b114eba9484e80c5bdf9437da78a1c9c4f/pages/%5BtermId%5D/%5Bquery%5D.tsx#L113 with th is, router.query doesn't populate the object until the page hydrates, which takes a few moments -- we're gonna have to render some empty search result in the mean time or some loading page. It really takes less than half a second, but it will null the page until then... which is why campus is right now hardcoded -- it depends on termId and termId doesn't set for a second

that will also affect the useState for termId, you're gonna hav eto set it after it hydrates
finally, with DropdownFilter.tsx, I think the reasons it's not properly styling has to do with this line change https://github.com/sandboxnu/searchneu/blob/57c530b114eba9484e80c5bdf9437da78a1c9c4f/components/ResultsPage/DropdownFilter.tsx#L3, though I don't know all of the details of scss and Next. Funnily enough, this is the only page that does this :grimacing:

and as documented above, we have some other weird splash page issues

**Comment by NEUDitao** [comment]
Also gonna want to look at the use of `window` everywhere -- already an issue in `user.js`. Gonna have to `useLocalStorage`

**Comment by dajinchu** [comment]
Importing Fullstory, rollbar, google analytics, and amplitude were all a bit odd. 
See: 
https://github.com/sandboxnu/searchneu/blob/nextjs/pages/_document.tsx

And google had to add a hook to register page views when the nextjs router changes pages https://github.com/sandboxnu/searchneu/blob/nextjs/utils/gtag.ts
